services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: localhost
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_DATABASE=jmail

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama

  mcp:
    image: gmail-mcp-server:latest
    ports:
      - "8000:8000"
    volumes:
      - ../.google:/app/.google
    environment:
      - CREDS_FILE_PATH=.google/client_creds.json
      - TOKEN_PATH=.google/app_tokens.json

