services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_DATABASE=moneypenny

  mcp:
    image: email-mcp-server:latest
    network_mode: host
    depends_on:
      - mongodb
    environment:
      - EMAIL_MCP_CLIENT_ID=${EMAIL_MCP_CLIENT_ID}
      - EMAIL_MCP_CLIENT_SECRET=${EMAIL_MCP_CLIENT_SECRET}
      - AUTH_URL=${AUTH_URL}
      - JWKS_URL=${JWKS_URL}

  moneypenny:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev
    network_mode: host
    depends_on:
      - mongodb
      - mcp
    environment:
      - MONEYPENNY_CLIENT_ID=${MONEYPENNY_CLIENT_ID}
      - MONEYPENNY_CLIENT_SECRET=${MONEYPENNY_CLIENT_SECRET}
      - EMAIL_MCP_CLIENT_ID=${EMAIL_MCP_CLIENT_ID}
      - AUTH_URL=${AUTH_URL}
      - JWKS_URL=${JWKS_URL}
